<?php

namespace AppBundle\Repository;

/**
 * ZipCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCodeRepository extends \Doctrine\ORM\EntityRepository implements ZipCodeRepositoryInterface
{
    public function getAllZipCodes()
    {
        $result = $this
            ->createQueryBuilder('zc')
            ->select('zc.code')
            ->getQuery()
            ->getScalarResult();

        return array_map('current', $result);
    }
}
