<?php

namespace AppBundle\Repository;

/**
 * ZipCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        return $this
            ->createQueryBuilder('zc')
            ->select('zc.code')
            ->getQuery()
            ->getResult();
    }
}
